# Generated by Django 4.2 on 2023-06-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attributecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Namecategory', models.CharField(max_length=200)),
                ('Imagecategory', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taxname', models.CharField(max_length=200)),
                ('Taxpercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=200)),
                ('UnitValue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Varients', models.CharField(choices=[('size', 'size'), ('addon', 'add-on'), ('extra', 'extra')], max_length=100)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('attributename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.attributecategory')),
            ],
        ),
    ]
