# Generated by Django 4.2 on 2023-05-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unitName',
            new_name='UnitName',
        ),
    ]
