# Generated by Django 4.2 on 2023-05-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_rename_unitname_unit_unitname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Namecategory', models.CharField(max_length=200)),
                ('Imagecategory', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
