# Generated by Django 4.2 on 2023-06-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category_Fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Is_for_sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Tax_Fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='Unit_Fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='Variant_fr',
            field=models.ManyToManyField(blank=True, null=True, to='restaurantapp.attributecategory'),
        ),
    ]
