# Generated by Django 4.2 on 2023-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taxname', models.CharField(max_length=200)),
                ('Taxpercentage', models.IntegerField()),
            ],
        ),
    ]
