# Generated by Django 4.2 on 2023-05-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='attrubute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeName', models.CharField(max_length=100)),
            ],
        ),
    ]
