# Generated by Django 4.2 on 2023-06-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_alter_product_is_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Variant_fr',
            field=models.ManyToManyField(blank=True, to='restaurantapp.attributecategory'),
        ),
    ]
