# Generated by Django 4.2 on 2023-05-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_attrubute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attrubute',
            new_name='attribute',
        ),
    ]
