# Generated by Django 4.2 on 2023-05-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0006_rename_attrubute_attribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attribute',
            new_name='attributecategory',
        ),
    ]
