# Generated by Django 4.2 on 2023-06-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0006_alter_product_variant_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Is_for_sale',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
