# Generated by Django 4.2 on 2023-06-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0007_alter_product_is_for_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_Address', models.TextField(blank=True, max_length=100, null=True)),
                ('GST_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Country_Code', models.IntegerField(blank=True, default=8, null=True)),
                ('Manufacturing_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
