# Generated by Django 4.2 on 2023-07-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0008_companyinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_Bill_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Purchasing_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Selling_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Manufacture_Date', models.DateTimeField(blank=True, null=True)),
                ('Expire_Date', models.DateTimeField(blank=True, null=True)),
                ('Product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.product')),
                ('Units', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.unit')),
            ],
        ),
    ]
