# Generated by Django 4.2 on 2023-07-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0009_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Expire_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Manufacture_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
