# Generated by Django 4.2 on 2023-07-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0010_alter_stock_expire_date_alter_stock_manufacture_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Fr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_fr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Production_RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Measurement', models.PositiveIntegerField(blank=True, null=True)),
                ('Production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.product_fr')),
                ('Raw_Material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.stock')),
            ],
        ),
    ]
