# Generated by Django 4.2 on 2023-07-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0011_product_fr_production_rawmaterial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Production_RawMaterial',
            new_name='ProductionRawMaterial',
        ),
    ]
