# Generated by Django 4.2 on 2023-08-03 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0013_alter_attribute_varients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attribute',
        ),
    ]
