# Generated by Django 4.2 on 2023-08-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0015_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributecategory',
            name='attributeName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
