# Generated by Django 4.2 on 2023-08-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0016_alter_attributecategory_attributename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Variant_fr',
        ),
    ]
