# Generated by Django 4.2 on 2023-08-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0017_remove_product_variant_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributecategory',
            name='add_On',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_on_product', to='restaurantapp.product'),
        ),
        migrations.AddField(
            model_name='attributecategory',
            name='add_on_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.product'),
        ),
        migrations.AddField(
            model_name='attributecategory',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_product', to='restaurantapp.product'),
        ),
        migrations.AddField(
            model_name='attributecategory',
            name='extra_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attributecategory',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attributecategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_product', to='restaurantapp.product'),
        ),
        migrations.AddField(
            model_name='attributecategory',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
