# Generated by Django 4.2 on 2023-08-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0018_attributecategory_add_on_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Fr',
            new_name='Production',
        ),
    ]
