# Generated by Django 4.2 on 2023-08-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0019_rename_product_fr_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionrawmaterial',
            old_name='Production',
            new_name='production',
        ),
    ]
