# Generated by Django 4.2 on 2023-08-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0020_rename_production_productionrawmaterial_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrawmaterial',
            name='Raw_Material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurantapp.stock'),
        ),
    ]
