# Generated by Django 4.2 on 2023-09-14 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0021_alter_productionrawmaterial_raw_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Units',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.unit'),
        ),
    ]
