# Generated by Django 4.2 on 2023-10-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0022_alter_stock_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributecategory',
            name='add_on_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
